#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 11 22:59:06 2021
@course: Python is Easy

@assignment: Homework #3

@description: "If" Statements

@author: Claus Derlien
"""
# first part
def equality(par1,par2,par3):
    result = False
    if (int(par1) != int(par2)) & (int(par1) != int(par3)) & (int(par2) != int(par3)):
        result = False
    else:
        result = True
    return result
        
# First part assuming all integers    
print(equality(1,2,3))  #False   
print(equality(3,3,3))  #True
print(equality(1,3,1))  #True  
print(equality(3,3,2))  #True
print(equality(1,3,3))  #True
print("---------------")
# second part proof that function works with strings and integers
print(equality("1",2,3))     #False   
print(equality(3,"3",3))     #True
print(equality(1,3,"1"))     #True  
print(equality("3",3,"2"))   #True
print(equality("1","3","3")) #True

